name: Test

on:
  push:
    branches:
      - 'main'
  release:
    types:
      - created

env:
  VERSION: ${{ github.event.release.tag_name != '' && github.event.release.tag_name || '0.0.0' }}

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - 
            os: ubuntu-20.04
            python_version: '3.8.18' # the latest version of 3.8.x
            sed: 'sed'
          - 
            os: windows-2019
            python_version: '3.8.18' # the latest version of 3.8.x
            sed: 'sed'
          - 
            os: macos-11
            python_version: '3.8.18' # the latest version of 3.8.x
            sed: 'gsed'

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Install gsed for macOS
        if: startsWith(matrix.os, 'macos-')
        shell: bash
        run: brew install gnu-sed

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}
          cache: 'pip'
          cache-dependency-path: |
            **/requirements-development.txt

      - name: Install Dependencies
        shell: bash
        run: |
            pip3 install -r requirements-development.txt
            pip3 install wheel

      - name: Replace version
        shell: bash
        run: |
          "${{ matrix.sed }}" -i "s/__VERSION__ = '0.0.0'/__VERSION__ = '${{ env.VERSION }}'/" liveinfo/__init__.py

      - name: Flake8
        shell: bash
        run: flake8

      - name: mypy
        shell: bash
        run: mypy .

      - name: pytest
        shell: bash
        run: pytest ./tests

      - name: Build
        shell: bash
        run: python3 setup.py sdist bdist_wheel

      - name: Build Binary
        run: |
          pyinstaller --name liveinfo --onefile main.py
